-- Create FAQs for Chauffagiste Saint-André-lez-Lille
INSERT INTO service_city_faqs (service_id, city_id, question, answer, position, published) VALUES
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Vos délais d''intervention à Saint-André (centre, Sainte-Hélène, bords de Deûle) ?', 'En urgence, nous intervenons en général sous 2 heures. Nous débutons par une mise en sécurité (contrôle gaz, ventilation, tirage/ventouse) et tentons une remise en route. Si une pièce spécifique est nécessaire, nous planifions un retour rapide. Notre proximité avec Lille garantit des délais courts, même en période froide.', 1, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Quel est le coût d''un entretien annuel de chaudière à Saint-André ?', 'Entre 120 et 160 € TTC selon le type (gaz, fioul, condensation). Inclus : nettoyage brûleur et corps de chauffe, contrôles de sécurité, mesure de combustion et attestation obligatoire. Cet entretien assure sécurité, durée de vie et rendement.', 2, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Intervenez-vous dans les maisons mitoyennes du centre-ville ?', 'Oui. Nous travaillons avec du matériel compact, protégeons systématiquement les sols et parties communes, et adaptons l''évacuation (ventouse/cheminée tubée) pour respecter l''existant. L''objectif : une intervention propre, conforme et durable.', 3, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Mes radiateurs chauffent mal à l''étage : quelles solutions proposez-vous ?', 'Souvent un déséquilibre ou de l''embouage. Nous vérifions la pression, purgeons, réglons les vannes thermostatiques, rééquilibrons les débits et recommandons un désembouage si l''eau est chargée. Résultat : chaleur homogène et consommation réduite.', 4, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Remplacez-vous des chaudières anciennes par des modèles à condensation compacts ?', 'Oui. Nous effectuons une étude de dimensionnement (surface, isolation, usages) pour choisir un modèle performant et compatible avec vos radiateurs/conduits. Prestation incluant dépose/évacuation, mise en service et réglages, plus conseils d''usage.', 5, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Proposez-vous des contrats d''entretien pour bailleurs/syndics à Saint-André ?', 'Oui, des contrats annuels pour maisons, appartements et résidences : visite planifiée, priorité en cas de panne, tarifs préférentiels sur certaines interventions. Coordination avec gardien/syndic pour limiter les coupures d''eau chaude.', 6, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Êtes-vous disponibles le week-end pour les pannes de chauffage ?', 'Oui, permanence le samedi et parfois le dimanche. Tarifs de week-end annoncés à l''avance. Nous sécurisons l''installation et, si besoin, assurons un dépannage provisoire avant la réparation définitive lorsque la pièce arrive.', 7, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 'Aides financières : puis-je en bénéficier pour remplacer ma chaudière à Saint-André ?', 'Selon votre situation, MaPrimeRénov'' et des primes énergie peuvent s''appliquer. Nous vous guidons sur l''éligibilité, les justificatifs et le calendrier pour optimiser budget et délais, et sélectionner un modèle éligible.', 8, true);