-- Create FAQs for Chauffagiste Lomme
INSERT INTO service_city_faqs (service_id, city_id, question, answer, position, published) VALUES
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Vos délais d''intervention à Lomme (Délivrance, Bourg, Mitterie, Mont-à-Camp) ?', 'En urgence, nous intervenons généralement sous 2 heures. Nous commençons par une mise en sécurité (contrôle gaz, ventilation, tirage/ventouse), puis tentons une remise en route. Si une pièce doit être commandée, nous planifions un retour rapide. Notre organisation par secteurs limite les temps de trajet, même en hiver.', 1, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Quel est le coût d''un entretien annuel de chaudière à Lomme ?', 'Entre 120 et 160 € TTC selon le type (gaz, fioul, condensation). Inclus : nettoyage brûleur et corps de chauffe, contrôles de sécurité, mesure de combustion et attestation obligatoire pour l''assurance. L''entretien garantit sécurité, durée de vie et rendement.', 2, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Intervenez-vous dans les pavillons de la Délivrance et les maisons mitoyennes ?', 'Oui. Nous protégeons systématiquement sols et escaliers, utilisons du matériel compact et adaptons l''évacuation (ventouse/cheminée tubée) pour respecter l''existant. Objectif : intervention propre, conforme et durable, avec explications d''usage.', 3, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Mes radiateurs chauffent mal à l''étage : quelles solutions proposez-vous ?', 'Souvent un déséquilibre ou de l''embouage. Nous vérifions la pression, purgeons, réglons les vannes thermostatiques, rééquilibrons les débits et recommandons un désembouage si l''eau est chargée. Résultat : chaleur homogène, montée en température plus rapide et consommation réduite.', 4, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Remplacez-vous des chaudières anciennes par des modèles à condensation compacts ?', 'Oui. Nous réalisons une étude de dimensionnement (surface, isolation, usages) pour choisir un modèle performant et compatible avec vos radiateurs et conduits. La prestation inclut dépose/évacuation, mise en service et réglages, plus conseils pour optimiser la conso.', 5, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Proposez-vous des contrats d''entretien pour bailleurs/syndics à Lomme ?', 'Oui, des contrats annuels pour maisons, appartements et résidences : visite planifiée, priorité en cas de panne, tarifs préférentiels sur certaines interventions. Coordination avec gardien/syndic pour limiter les coupures d''eau chaude.', 6, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Êtes-vous disponibles le week-end pour les pannes de chauffage ?', 'Oui, permanence le samedi et parfois le dimanche. Tarifs de week-end annoncés à l''avance. Nous sécurisons l''installation et, si besoin, assurons un dépannage provisoire avant la réparation définitive dès réception de la pièce.', 7, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lomme'), 'Aides financières : puis-je en bénéficier pour remplacer ma chaudière à Lomme ?', 'Selon votre situation, MaPrimeRénov'' et des primes énergie peuvent s''appliquer. Nous vous guidons sur l''éligibilité, les justificatifs et le calendrier pour optimiser budget et délais, et sélectionner un modèle éligible.', 8, true);