-- Create FAQs for Chauffagiste La Madeleine
INSERT INTO service_city_faqs (service_id, city_id, question, answer, position, published) VALUES
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Quels sont vos délais d''intervention à La Madeleine (Saint-Maur, Botanique, Berkem) ?', 'En urgence, nous intervenons généralement sous 2 heures. Nous débutons par une mise en sécurité (contrôles gaz, ventilation, tirage/ventouse), puis tentons une remise en route. Si une pièce spécifique est nécessaire, nous organisons un retour rapide. Notre proximité avec Lille garantit des délais courts, même en hiver.', 1, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Quel est le coût d''un entretien annuel de chaudière à La Madeleine ?', 'Entre 120 et 160 € TTC selon le type (gaz, fioul, condensation). Inclus : nettoyage brûleur/corps de chauffe, vérification des organes de sécurité, mesure de combustion et attestation obligatoire. Cet entretien est essentiel pour la sécurité, la durabilité et la couverture assurance.', 2, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Intervenez-vous dans les copropriétés de Saint-Maur et du centre ?', 'Oui. Habitués aux cages étroites et locaux techniques en sous-sol, nous protégeons parties communes et planifions avec gardien/syndic (affichage, coupures d''eau chaude si besoin). Pour colonnes collectives, nous privilégions les méthodes non destructives et limitons les nuisances.', 3, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Remplacez-vous les chaudières anciennes par des modèles à condensation compacts ?', 'Oui. Nous réalisons une étude de dimensionnement (surface, isolation, usages) et sélectionnons un modèle compact et performant compatible avec l''existant (radiateurs, conduit/ventouse). Prestation incluant dépose/évacuation, mise en service et réglages.', 4, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Mes radiateurs chauffent mal au dernier étage : que proposez-vous ?', 'Souvent un problème d''équilibrage ou d''embouage. Nous contrôlons pression et débits, purgeons, réglons les vannes thermostatiques et recommandons un désembouage si l''eau est chargée. Résultat : montée en température plus rapide et confort homogène.', 5, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Proposez-vous des contrats d''entretien pour bailleurs/syndics à La Madeleine ?', 'Oui, des contrats annuels pour appartements, maisons et résidences : visite planifiée, priorité en cas de panne, tarifs préférentiels sur certaines interventions. Coordination avec syndic pour limiter la gêne et respecter les créneaux des résidents.', 6, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Êtes-vous disponibles le week-end en cas de panne de chauffage ?', 'Oui, permanence le samedi et parfois le dimanche. Tarifs de week-end communiqués à l''avance. Nous sécurisons l''installation et mettons en place un dépannage provisoire si une pièce doit être commandée, puis réparons définitivement.', 7, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 'Puis-je bénéficier d''aides pour remplacer ma chaudière à La Madeleine ?', 'Selon votre situation, MaPrimeRénov'' et des primes énergie peuvent s''appliquer. Nous vous aidons à évaluer l''éligibilité, à rassembler les justificatifs et à planifier le calendrier pour optimiser budget et délais.', 8, true);