-- Ajouter les FAQs locales pour serrurier
INSERT INTO service_city_faqs (service_id, city_id, position, question, answer, published) VALUES

-- Lille FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 1, 'Pouvez-vous intervenir en urgence à Lille ?', 'Oui, nos serruriers se déplacent sous 30 à 45 minutes dans Lille intra-muros, y compris Vieux-Lille, Wazemmes et Vauban. Dépannage prioritaire la nuit et le week-end.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 2, 'Ouverture de porte : abîmez-vous la serrure ?', 'Nous privilégions les méthodes non destructives (radio, crochetage fin). Si la serrure est endommagée ou trop sécurisée, nous proposons immédiatement un remplacement.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 3, 'Quels types de serrures installez-vous à Lille ?', 'Nous posons des cylindres européens, serrures multipoints 3 à 7 points certifiées A2P, verrous et solutions connectées. Nous adaptons selon votre budget et vos besoins.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 4, 'Intervenez-vous après effraction ?', 'Oui, nous sécurisons immédiatement la porte fracturée, posons un cylindre provisoire et établissons un devis détaillé agréé assurances.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 5, 'Proposez-vous des portes blindées à Lille ?', 'Oui, installation de blindages et portes blindées certifiées BP1 à BP3, avec cornières anti-pinces et renforts de huisseries.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 6, 'Quels quartiers de Lille couvrez-vous ?', 'Nous intervenons partout : Vieux-Lille, Centre, Vauban, Wazemmes, Fives, Hellemmes, Lomme et périphérie (Mons, La Madeleine, Lambersart).', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 7, 'Puis-je être remboursé par mon assurance après cambriolage ?', 'Oui. Nous vous remettons facture et attestation conformes pour remboursement auprès de votre assurance habitation.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lille'), 8, 'Faites-vous aussi des audits sécurité à Lille ?', 'Oui, nous analysons portes, serrures et fenêtres, et proposons un devis clair pour renforcer vos accès.', true),

-- Vieux-Lille FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 1, 'Intervenez-vous dans les immeubles anciens du Vieux-Lille ?', 'Oui. Nous protégeons les parties communes, limitons le bruit et utilisons des techniques d''ouverture fines adaptées aux portes anciennes.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 2, 'Les portes anciennes acceptent-elles les serrures multipoints ?', 'Oui, après ajustements : renfort huisserie, pose discrète. Nous proposons des modèles compatibles avec le bâti ancien.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 3, 'Comment sécurisez-vous un appartement ancien après effraction ?', 'Nous posons un cylindre provisoire, renforçons la porte et remettons un devis assurances. Nous intervenons souvent rue Royale, rue Basse, rue Esquermoise.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 4, 'Quels délais pour une ouverture de porte claquée au Vieux-Lille ?', '30 à 45 minutes selon circulation et accès (rues étroites). Nos serruriers connaissent les contraintes locales.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 5, 'Installez-vous des serrures connectées en appartement ancien ?', 'Oui, serrures électroniques compatibles badges ou smartphones, adaptées aux portes existantes.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 6, 'Proposez-vous un blindage discret ?', 'Oui, blindage intérieur ou cornières anti-pinces, intégrés esthétiquement sans dénaturer la façade.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 7, 'Coordonnez-vous avec les syndics ?', 'Oui, pour accès aux parties communes, gestion badges VIGIK et autorisations d''intervention.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 8, 'Votre travail est-il couvert par une garantie ?', 'Oui, garantie décennale sur les ouvrages et garantie biennale sur les équipements installés.', true),

-- Villeneuve-d'Ascq FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 1, 'Pouvez-vous intervenir en résidence étudiante à Villeneuve-d''Ascq ?', 'Oui, nous intervenons régulièrement dans les campus (Pont-de-Bois, Triolo, Hôtel de Ville). Délais rapides pour portes claquées ou clés perdues.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 2, 'Quels types de serrures conseillez-vous pour les maisons ascquoises ?', 'Nous recommandons serrures multipoints 5 à 7 points A2P pour maisons de Brigode, Flers-Bourg, Annappes.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 3, 'Faites-vous des interventions le soir et week-end ?', 'Oui, nous assurons un service 24/7 pour urgences (perte de clés, cambriolage).', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 4, 'Remplacez-vous aussi les portes après effraction ?', 'Oui, en coordination avec nos menuisiers partenaires. Sécurisation immédiate et devis assurance fourni.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 5, 'Installez-vous des verrous additionnels ?', 'Oui, verrous de sûreté, barres de blocage, solutions connectées simples pour studios.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 6, 'Proposez-vous des solutions PMR/seniors ?', 'Oui, poignées adaptées, serrures à clés ergonomiques, barres de renfort faciles à manipuler.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 7, 'Quels délais pour changer un cylindre ?', 'Remplacement sous 2 h en moyenne sur Villeneuve-d''Ascq et communes voisines.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 8, 'Puis-je avoir un devis gratuit ?', 'Oui, nos devis sont gratuits et détaillés, remis avant toute intervention.', true),

-- Marcq-en-Barœul FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 1, 'Pouvez-vous intervenir rapidement au Croisé-Laroche ?', 'Oui, délai moyen 30 minutes. Serruriers disponibles pour ouvertures et sécurisations.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 2, 'Quels systèmes installez-vous pour sécuriser une maison à Marcq ?', 'Serrures multipoints, blindages de portes, portes blindées BP1 à BP3.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 3, 'Vos serrures sont-elles agréées assurances ?', 'Oui, serrures certifiées A2P 1 à 3 étoiles reconnues par assureurs.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 4, 'Faites-vous des portes blindées sur mesure ?', 'Oui, pour maisons bourgeoises du Bourg ou du Croisé, intégrées au style existant.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 5, 'Comment se passe une réparation après cambriolage ?', 'Nous sécurisons immédiatement la porte fracturée, remplaçons cylindre et huisserie, devis remis pour assurance.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 6, 'Quels quartiers de Marcq couvrez-vous ?', 'Croisé-Laroche, Bourg, Plouich, Hippodrome, Pont, Rouges-Barres, limite Wasquehal/La Madeleine.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 7, 'Proposez-vous des solutions connectées ?', 'Oui, serrures électroniques à code, badge ou smartphone, adaptées aux familles.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 8, 'Quels sont vos horaires ?', 'Disponibles 24h/24 et 7j/7 pour urgences comme pour rendez-vous planifiés.', true),

-- Bondues FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 1, 'Intervenez-vous sur les grandes propriétés de Bondues ?', 'Oui, nous équipons villas et maisons avec serrures multipoints, cylindres haute sécurité et contrôles d''accès.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 2, 'Proposez-vous du blindage haut de gamme ?', 'Oui, blindage de portes avec finitions esthétiques, intégration discrète, cornières anti-pinces.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 3, 'Quels délais pour une ouverture de porte à Bondues ?', 'En moyenne 30 minutes, selon secteur (Montjoie, Ravennes-les-Francs).', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 4, 'Vos équipements sont-ils certifiés ?', 'Oui, serrures A2P, cylindres anti-perçage, anti-bumping, conformes aux normes assurances.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 5, 'Proposez-vous des audits sécurité ?', 'Oui, analyse complète des accès, devis pour assurances, recommandations sur mesure.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 6, 'Installez-vous des portes blindées ?', 'Oui, portes blindées certifiées, pose discrète adaptée aux villas.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 7, 'Faites-vous aussi les dépendances et garages ?', 'Oui, sécurisation des annexes, dépendances et bureaux attenants.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'bondues'), 8, 'Garantissez-vous vos interventions ?', 'Oui, garantie décennale pour blindage/portes, biennale pour serrures.', true),

-- La Madeleine FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 1, 'Pouvez-vous intervenir en copropriété à La Madeleine ?', 'Oui, nous respectons règlements de copropriété (Saint-Maur, Botanique), protégeons parties communes et prévenons syndics.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 2, 'Délais pour une ouverture de porte claquée ?', 'Environ 30 minutes, accès rapide depuis Lille et Marcq.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 3, 'Proposez-vous des serrures multipoints pour appartements ?', 'Oui, modèles adaptés aux portes palières, certifiés A2P.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 4, 'Comment sécurisez-vous après effraction ?', 'Pose de cylindre provisoire, renforts de porte, devis assurance inclus.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 5, 'Faites-vous des blindages discrets ?', 'Oui, blindages intérieurs et cornières, respect esthétique du bâti.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 6, 'Installez-vous des verrous additionnels ?', 'Oui, verrous de sûreté et solutions renforcées pour studios.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 7, 'Quels quartiers de La Madeleine couvrez-vous ?', 'Saint-Maur, Botanique, centre, Berkem, Romarin, proche Euralille.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 8, 'Vos travaux sont-ils garantis ?', 'Oui, décennale pour blindage, biennale pour serrures posées.', true),

-- Lambersart FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 1, 'Intervenez-vous dans les maisons bourgeoises de Lambersart ?', 'Oui, ouverture et blindage adaptés aux portes anciennes de Canteleu, Pacot-Vandracq, Champ-de-Courses.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 2, 'Posez-vous des serrures multipoints A2P ?', 'Oui, serrures 3 à 7 points certifiées A2P, reconnues par assurances.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 3, 'Proposez-vous des blindages discrets ?', 'Oui, blindages intérieurs, cornières anti-pinces, finitions haut de gamme.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 4, 'Quels délais pour un dépannage à Lambersart ?', '30 minutes en moyenne, disponibilité 24/7 pour urgences.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 5, 'Faites-vous des réparations après effraction ?', 'Oui, sécurisation immédiate, remplacement serrure, devis assurance.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 6, 'Proposez-vous des portes blindées ?', 'Oui, portes blindées BP1 à BP3 adaptées maisons bourgeoises.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 7, 'Avez-vous des solutions pour seniors/PMR ?', 'Oui, poignées ergonomiques, serrures faciles à manipuler, seuils adaptés.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lambersart'), 8, 'Vos interventions sont-elles garanties ?', 'Oui, décennale et biennale selon travaux réalisés.', true),

-- Saint-André-lez-Lille FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 1, 'Pouvez-vous intervenir en maison mitoyenne ?', 'Oui, nous adaptons nos méthodes aux accès étroits, évacuations et huisseries spécifiques.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 2, 'Délais pour une ouverture de porte à Saint-André ?', '30 minutes en moyenne, selon circulation. Serruriers locaux disponibles 24/7.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 3, 'Faites-vous des serrures multipoints renforcées ?', 'Oui, serrures 3 à 7 points A2P pour portes d''appartements et maisons.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 4, 'Intervenez-vous après cambriolage ?', 'Oui, sécurisation immédiate, devis assurance, remplacement rapide.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 5, 'Proposez-vous des blindages de portes ?', 'Oui, blindages intérieurs ou portes blindées complètes.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 6, 'Couvrez-vous tous les quartiers ?', 'Centre, Sainte-Hélène, bords de Deûle, proximité gare.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 7, 'Avez-vous des solutions pour studios ?', 'Oui, verrous de sûreté et serrures compactes adaptées.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 8, 'Vos services sont-ils garantis ?', 'Oui, décennale/biennale selon interventions.', true),

-- Lomme FAQs
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 1, 'Pouvez-vous intervenir rapidement à Lomme ?', 'Oui, 30 minutes en moyenne dans tous les quartiers : Délivrance, Bourg, Mitterie, Mont-à-Camp.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 2, 'Quels services proposez-vous en serrurerie à Lomme ?', 'Ouverture de portes, changement de barillets, serrures multipoints, blindages, réparations après effraction.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 3, 'Proposez-vous des blindages à Lomme ?', 'Oui, blindages simples ou renforcés, adaptés à chaque type de porte.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 4, 'Travaillez-vous avec les assurances ?', 'Oui, devis et factures agréés pour remboursements après cambriolage.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 5, 'Intervenez-vous le week-end et jours fériés ?', 'Oui, astreinte 24/7 pour urgences serrurerie.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 6, 'Installez-vous des portes blindées ?', 'Oui, portes blindées BP1 à BP3, adaptées pavillons et appartements.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 7, 'Proposez-vous des solutions connectées ?', 'Oui, serrures électroniques compatibles badges et smartphones.', true),
((SELECT id FROM services WHERE slug = 'serrurier'), (SELECT id FROM cities WHERE slug = 'lomme'), 8, 'Vos travaux sont-ils garantis ?', 'Oui, décennale pour blindage/portes, biennale pour serrures.', true);