-- Ajouter les offres pour chaque page service-ville serrurier
INSERT INTO service_city_offers (page_id, position, title, description, icon_name, emoji) VALUES

-- Lille
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 1, 'Ouverture de porte à Lille', 'Ouverture sans casse quand possible (porte claquée, clés oubliées). Méthodes fines adaptées aux serrures courantes.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 2, 'Changement de cylindre/barillet', 'Remplacement immédiat de cylindre simple ou haute sécurité. Large choix de modèles certifiés.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 3, 'Serrures multipoints', 'Pose ou remplacement de serrures 3 à 7 points certifiées A2P pour une sécurité renforcée.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 4, 'Réparation après effraction', 'Remise en sécurité de porte fracturée, remplacement de serrures, huisseries consolidées.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 5, 'Blindage de porte', 'Installation de tôle de blindage, cornières anti-pinces et serrures multipoints.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lille')), 6, 'Conseil sécurité', 'Audit sécurité habitation/professionnels, devis assurance, solutions personnalisées.', '', '📋'),

-- Vieux-Lille
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 1, 'Ouverture en immeuble ancien', 'Ouverture discrète de portes anciennes, respect des boiseries et finitions.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 2, 'Remplacement de cylindres anciens', 'Cylindres compatibles avec serrures anciennes, sécurité renforcée.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 3, 'Serrures multipoints adaptées', 'Pose de multipoints A2P sur portes anciennes, ajustements sur mesure.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 4, 'Réparation après cambriolage', 'Sécurisation rapide, huisseries renforcées, devis assurance inclus.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 5, 'Renforts discrets', 'Cornières anti-pinces et blindages adaptés aux bâtis patrimoniaux.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'vieux-lille')), 6, 'Gestion copropriété', 'Badges, VIGIK, digicodes, coordination syndic.', '', '📋'),

-- Villeneuve-d'Ascq
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 1, 'Ouverture de porte', 'Ouverture rapide dans résidences étudiantes et maisons familiales.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 2, 'Changement de barillet', 'Remplacement rapide, barillets sécurisés adaptés à vos portes.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 3, 'Pose multipoints', 'Installation de serrures 3 à 7 points pour maisons et appartements.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 4, 'Réparation après effraction', 'Mise en sécurité et remplacement des serrures endommagées.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 5, 'Sécurisation résidences étudiantes', 'Solutions robustes pour studios et colocations.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq')), 6, 'Conseil sécurité', 'Évaluation et devis clair, adaptation familles/étudiants.', '', '📋'),

-- Marcq-en-Barœul
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 1, 'Ouverture de porte', 'Ouverture fine sans destruction, délais rapides.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 2, 'Cylindres européens', 'Remplacement de barillets haute sécurité, anti-crochetage.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 3, 'Serrures multipoints', 'Pose de serrures A2P certifiées, 3 à 7 points.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 4, 'Réparation après effraction', 'Remise en état rapide, devis assurance immédiat.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 5, 'Blindage de porte', 'Solutions anti-effraction adaptées aux maisons bourgeoises.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul')), 6, 'Porte blindée', 'Installation de portes blindées certifiées A2P BP1 à BP3.', '', '📋'),

-- Bondues
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 1, 'Ouverture de porte', 'Ouverture soignée, respect des huisseries haut de gamme.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 2, 'Remplacement de barillets', 'Cylindres haute sécurité anti-perçage et anti-bumping.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 3, 'Serrures multipoints premium', 'Pose de serrures certifiées A2P pour villas et maisons.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 4, 'Réparation après cambriolage', 'Sécurisation immédiate, huisseries consolidées.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 5, 'Blindage haut de gamme', 'Blindage de portes avec finitions esthétiques.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'bondues')), 6, 'Audit sécurité', 'Analyse complète des accès, devis pour assurances.', '', '📋'),

-- La Madeleine
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 1, 'Ouverture de porte', 'Ouverture rapide et discrète, respect copropriété.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 2, 'Changement de cylindre', 'Remplacement barillet simple ou haute sécurité.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 3, 'Multipoints pour copro', 'Pose de serrures multipoints adaptées aux appartements.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 4, 'Réparation après effraction', 'Sécurisation rapide, coordination avec syndic/assurance.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 5, 'Renforts copro', 'Cornières anti-pinces et blindages discrets.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'la-madeleine')), 6, 'Gestion accès', 'Badges, digicodes, coordination syndic.', '', '📋'),

-- Lambersart
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 1, 'Ouverture de porte', 'Ouverture fine, respect des boiseries bourgeoises.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 2, 'Remplacement de cylindre', 'Cylindres renforcés, compatibles portes anciennes.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 3, 'Serrures multipoints', 'Installation certifiée A2P pour pavillons/maisons bourgeoises.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 4, 'Réparation après cambriolage', 'Sécurisation des accès, consolidation des huisseries.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 5, 'Blindage discret', 'Blindage et cornières anti-pinces, finitions premium.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lambersart')), 6, 'Conseils sécurité', 'Audit complet, recommandations adaptées.', '', '📋'),

-- Saint-André-lez-Lille
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 1, 'Ouverture de porte', 'Ouverture rapide en maison mitoyenne/appartement.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 2, 'Changement de barillet', 'Barillets sécurisés, remplacement express.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 3, 'Multipoints renforcés', 'Pose de serrures 3 à 7 points certifiées A2P.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 4, 'Réparation après effraction', 'Mise en sécurité portes fracturées, devis assurance.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 5, 'Renforts sécurisés', 'Paumelles, cornières et huisseries consolidées.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille')), 6, 'Conseils sur mesure', 'Audit sécurité adapté maisons mitoyennes.', '', '📋'),

-- Lomme
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 1, 'Ouverture de porte', 'Ouverture rapide toutes marques de serrures.', '', '🔑'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 2, 'Changement de barillet', 'Remplacement immédiat avec barillets de qualité.', '', '🛠'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 3, 'Serrures multipoints', 'Pose de serrures multipoints pour appartements/pavillons.', '', '🔒'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 4, 'Réparation après cambriolage', 'Remise en état, devis assurance inclus.', '', '🚨'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 5, 'Blindage de porte', 'Blindage simple ou renforcé selon configuration.', '', '🛡'),
((SELECT id FROM service_city_pages WHERE service_id = (SELECT id FROM services WHERE slug = 'serrurier') AND city_id = (SELECT id FROM cities WHERE slug = 'lomme')), 6, 'Conseils sécurité', 'Diagnostic sécurité habitation, devis clair.', '', '📋');