-- Import service_city_offers with proper foreign key mapping
INSERT INTO service_city_offers (page_id, position, emoji, icon_name, title, description)
SELECT 
  p.id as page_id,
  offers.position,
  offers.emoji,
  offers.icon_name,
  offers.title,
  offers.description
FROM (VALUES 
  ('plombier', 'lille', 1, '🚰', '', 'Réparation de fuite d''eau à Lille', 'Localisation et réparation durable (tuyauterie, robinetterie, joints, chauffe-eau).'),
  ('plombier', 'lille', 2, '🛠', '', 'Débouchage de canalisation', 'Évier, lavabo, douche, WC : furet électrique, pompe HP, intervention sans dégâts.'),
  ('plombier', 'lille', 3, '🔥', '', 'Remplacement de ballon d''eau chaude', 'Conseil modèle (électrique/thermodynamique), dépose/pose et évacuation.'),
  ('plombier', 'lille', 4, '💧', '', 'Installation d''adoucisseur d''eau', 'Protection contre le calcaire, accompagnement du choix à la mise en service.'),
  ('plombier', 'lille', 5, '🛁', '', 'Devis rénovation salle de bains', 'Douche à l''italienne, optimisation de l''espace, coordination corps d''état.'),
  ('plombier', 'lille', 6, '🔧', '', 'Entretien et rénovation de plomberie', 'Mise aux normes, remplacement de tuyauterie et robinetterie.'),
  ('plombier', 'vieux-lille', 1, '🚰', '', 'Réparation de fuite d''eau Vieux-Lille', 'Intervention soignée dans les intérieurs du centre historique.'),
  ('plombier', 'vieux-lille', 2, '🛠', '', 'Débouchage canalisation', 'Traitement rapide sans détérioration des finitions.'),
  ('plombier', 'vieux-lille', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Diagnostic et remplacement maîtrisé en habitat collectif/ancien.'),
  ('plombier', 'vieux-lille', 4, '💧', '', 'Installation d''adoucisseur', 'Réduction du tartre, confort sanitaire et longévité des appareils.'),
  ('plombier', 'vieux-lille', 5, '🛁', '', 'Rénovation salle de bains', 'Solutions compactes et esthétiques adaptées aux surfaces du centre.'),
  ('plombier', 'vieux-lille', 6, '🔧', '', 'Entretien & rénovation', 'Mise aux normes réseau, robinetterie, étanchéité.'),
  ('plombier', 'villeneuve-d-ascq', 1, '🚰', '', 'Réparation de fuite d''eau', 'Recherche de fuite et remise en état en habitat étudiant/pavillonnaire.'),
  ('plombier', 'villeneuve-d-ascq', 2, '🛠', '', 'Débouchage canalisation', 'Cuisine, salle de bains, WC : matériel pro pour un écoulement rétabli.'),
  ('plombier', 'villeneuve-d-ascq', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Conseils adaptés à la conso familiale, pose propre et sécurisée.'),
  ('plombier', 'villeneuve-d-ascq', 4, '💧', '', 'Adoucisseur d''eau', 'Protection anti-calcaire sur réseaux de la MEL.'),
  ('plombier', 'villeneuve-d-ascq', 5, '🛁', '', 'Rénovation salle de bains', 'Projets clé en main (étudiants/familles) avec planning optimisé.'),
  ('plombier', 'villeneuve-d-ascq', 6, '🔧', '', 'Entretien & rénovation', 'Mises aux normes, joints, tuyauterie, petits travaux rapides.'),
  ('plombier', 'marcq-en-baroeul', 1, '🚰', '', 'Réparation de fuite d''eau', 'Diagnostic précis et finitions soignées (maisons/appartements).'),
  ('plombier', 'marcq-en-baroeul', 2, '🛠', '', 'Débouchage canalisation', 'Pompe HP, furet électrique, intervention propre au Croisé-Laroche et ailleurs.'),
  ('plombier', 'marcq-en-baroeul', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Remplacement toutes capacités, évacuation de l''ancien.'),
  ('plombier', 'marcq-en-baroeul', 4, '💧', '', 'Adoucisseur d''eau', 'Protection anti-tartre, choix d''équipement et mise en service.'),
  ('plombier', 'marcq-en-baroeul', 5, '🛁', '', 'Rénovation salle de bains', 'Devis détaillé, coordination carrelage/électricité.'),
  ('plombier', 'marcq-en-baroeul', 6, '🔧', '', 'Entretien & rénovation', 'Mise aux normes, réparations réseau plomberie.'),
  ('plombier', 'bondues', 1, '🚰', '', 'Réparation de fuite d''eau', 'Recherche et réparation sans sur-travaux.'),
  ('plombier', 'bondues', 2, '🛠', '', 'Débouchage canalisation', 'Eaux usées, pluviales : matériel pro.'),
  ('plombier', 'bondues', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Conseil modèle, pose et évacuation.'),
  ('plombier', 'bondues', 4, '💧', '', 'Adoucisseur d''eau', 'Protection réseaux domestiques, entretien.'),
  ('plombier', 'bondues', 5, '🛁', '', 'Rénovation salle de bains', 'Chantiers clé en main pour maisons familiales.'),
  ('plombier', 'bondues', 6, '🔧', '', 'Entretien & rénovation', 'Mises aux normes et réparations.'),
  ('plombier', 'la-madeleine', 1, '🚰', '', 'Réparation de fuite d''eau', 'Interventions rapides en habitat collectif et maisons.'),
  ('plombier', 'la-madeleine', 2, '🛠', '', 'Débouchage canalisation', 'Traitement évier/WC/douche, inspection si besoin.'),
  ('plombier', 'la-madeleine', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Approvisionnement et pose express.'),
  ('plombier', 'la-madeleine', 4, '💧', '', 'Adoucisseur d''eau', 'Anti-calcaire, réglages et mise en route.'),
  ('plombier', 'la-madeleine', 5, '🛁', '', 'Rénovation salle de bains', 'Devis détaillé, coordination corps d''état.'),
  ('plombier', 'la-madeleine', 6, '🔧', '', 'Entretien & rénovation', 'Petites réparations, robinetterie, joints.'),
  ('plombier', 'lambersart', 1, '🚰', '', 'Réparation de fuite d''eau', 'Localisation et réparation durable.'),
  ('plombier', 'lambersart', 2, '🛠', '', 'Débouchage canalisation', 'Furet électrique, pompe HP.'),
  ('plombier', 'lambersart', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Conseil, pose et évacuation ancien.'),
  ('plombier', 'lambersart', 4, '💧', '', 'Adoucisseur d''eau', 'Protection anti-calcaire, confort.'),
  ('plombier', 'lambersart', 5, '🛁', '', 'Rénovation salle de bains', 'Projets clé en main.'),
  ('plombier', 'lambersart', 6, '🔧', '', 'Entretien & rénovation', 'Mise aux normes, réparations.'),
  ('plombier', 'saint-andre-lez-lille', 1, '🚰', '', 'Réparation de fuite d''eau', 'Diagnostic et réparation rapide.'),
  ('plombier', 'saint-andre-lez-lille', 2, '🛠', '', 'Débouchage canalisation', 'Cuisine, SDB, WC : matériel pro.'),
  ('plombier', 'saint-andre-lez-lille', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Fourniture et pose.'),
  ('plombier', 'saint-andre-lez-lille', 4, '💧', '', 'Adoucisseur d''eau', 'Anti-calcaire domestique.'),
  ('plombier', 'saint-andre-lez-lille', 5, '🛁', '', 'Rénovation salle de bains', 'Clé en main, devis gratuit.'),
  ('plombier', 'saint-andre-lez-lille', 6, '🔧', '', 'Entretien & rénovation', 'Petits travaux, mises aux normes.'),
  ('plombier', 'lomme', 1, '🚰', '', 'Réparation de fuite d''eau', 'Recherche et colmatage.'),
  ('plombier', 'lomme', 2, '🛠', '', 'Débouchage canalisation', 'Intervention propre, écoulement rétabli.'),
  ('plombier', 'lomme', 3, '🔥', '', 'Remplacement ballon d''eau chaude', 'Pose sécurisée et évacuation ancien.'),
  ('plombier', 'lomme', 4, '💧', '', 'Adoucisseur d''eau', 'Protection anti-tartre pour la maison.'),
  ('plombier', 'lomme', 5, '🛁', '', 'Rénovation salle de bains', 'Douche à l''italienne, optimisation espace.'),
  ('plombier', 'lomme', 6, '🔧', '', 'Entretien & rénovation', 'Réseau, joints, robinetterie.')
) AS offers(service_slug, city_slug, position, emoji, icon_name, title, description)
JOIN service_city_pages p ON p.service_id = (SELECT id FROM services WHERE slug = offers.service_slug)
  AND p.city_id = (SELECT id FROM cities WHERE slug = offers.city_slug)
ON CONFLICT (page_id, position) DO UPDATE SET 
  emoji = EXCLUDED.emoji,
  icon_name = EXCLUDED.icon_name,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  updated_at = now();