-- Create FAQs for Chauffagiste Lambersart
INSERT INTO service_city_faqs (service_id, city_id, question, answer, position, published) VALUES
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Vos délais d''intervention à Lambersart (Canteleu, Pacot-Vandracq, Champ-de-Courses, Bourg) ?', 'En urgence, nous intervenons en général sous 2 heures. Nous commençons par une mise en sécurité (contrôle gaz, ventilation, tirage/ventouse), puis tentons la remise en route. Si une pièce doit être commandée, nous planifions un retour rapide. Notre organisation par secteurs limite les temps de trajet, même en hiver.', 1, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Quel est le coût d''un entretien annuel de chaudière à Lambersart ?', 'Entre 120 et 160 € TTC selon le type (gaz, fioul, condensation). Inclus : nettoyage brûleur et corps de chauffe, contrôles de sécurité, mesure de combustion et attestation obligatoire pour l''assurance. Cet entretien garantit sécurité, durée de vie et rendement.', 2, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Intervenez-vous dans les maisons bourgeoises de Canteleu ?', 'Oui. Nous protégeons systématiquement parquets, boiseries et escaliers (bâches, sur-chaussures). En chaufferie ou cuisine, nous travaillons avec du matériel compact et adaptons l''évacuation (ventouse/cheminée tubée) pour respecter l''existant. Objectif : intervention propre, conforme et durable.', 3, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Mes radiateurs chauffent mal à l''étage : que proposez-vous ?', 'Souvent un déséquilibre ou de l''embouage. Nous contrôlons la pression, purgeons, réglons les vannes thermostatiques, rééquilibrons les débits et proposons un désembouage si l''eau est chargée. Résultat : chaleur homogène, montée en température plus rapide et consommation en baisse.', 4, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Remplacez-vous les anciennes chaudières par des modèles à condensation compacts ?', 'Oui. Nous réalisons une étude de dimensionnement (surface, isolation, usages) pour choisir un modèle performant et compatible avec vos radiateurs et conduits. La prestation inclut dépose/évacuation, mise en service et réglages, avec explications d''usage.', 5, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Proposez-vous des contrats d''entretien pour bailleurs/syndics à Lambersart ?', 'Oui, des contrats annuels pour maisons, appartements et résidences : visite planifiée, priorité en cas de panne, tarifs préférentiels sur certaines interventions. Coordination avec gardien/syndic pour limiter les coupures d''eau chaude.', 6, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Êtes-vous disponibles le week-end pour les pannes de chauffage ?', 'Oui, permanence le samedi et parfois le dimanche. Tarifs de week-end annoncés à l''avance. Nous sécurisons l''installation et, si besoin, assurons un dépannage provisoire avant la réparation définitive une fois la pièce reçue.', 7, true),
  ((SELECT id FROM services WHERE slug = 'chauffagiste'), (SELECT id FROM cities WHERE slug = 'lambersart'), 'Aides financières : puis-je en bénéficier pour remplacer ma chaudière à Lambersart ?', 'Selon votre situation, MaPrimeRénov'' et des primes énergie peuvent s''appliquer. Nous vous guidons sur l''éligibilité, les justificatifs et le calendrier pour optimiser budget et délais, et sélectionner un modèle éligible.', 8, true);