-- Continue adding FAQs for remaining cities
INSERT INTO service_city_faqs (service_id, city_id, position, question, answer, published)
VALUES
  -- Marcq-en-Barœul FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 1, 'Maisons bourgeoises (Croisé-Laroche/Bourg) : précautions ?', 'Protection des boiseries/escaliers, percements limités, reprises parfaites. Intégration de baignoires îlot et douches italiennes spacieuses.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 2, 'Douche italienne grand format : structure et étanchéité ?', 'Nattes d''étanchéité, pentes 1–2 %, caniveau inox, relevés en plinthes, tests d''arrosage avant carrelage.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 3, 'Éclairage haut de gamme : que proposez-vous ?', 'Spots LED IP65, miroirs rétroéclairés antibuée, bandeaux LED niches, variateurs compatibles volumes humides.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 4, 'Plomberie : améliorez-vous le confort ?', 'Mitigeurs thermostatiques, débit/pression équilibrés, insonorisation des évacuations, anti-bélier si nécessaire.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 5, 'PMR/seniors à Marcq : intégration élégante ?', 'Parois transparentes, barres finition inox brossé, sièges design, sols R10/R11, contrastes visuels et éclairage renforcé.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 6, 'Délais et présence sur site ?', '7–10 jours. Chef de chantier présent aux étapes clés (réseaux, étanchéité, pose carrelage, finitions).', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 7, 'Gestion poussière et propreté ?', 'Aspiration continue, zones confinées, bâches zip, nettoyage quotidien, remise en état en fin de chantier.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'marcq-en-baroeul'), 8, 'Suivi et documents finaux ?', 'Dossier photos avant/après, notices, plan as-built, fiche d''entretien et coordonnées SAV.', true),

  -- Bondues FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 1, 'Grandes salles de bains/villas : quelles spécificités ?', 'Parcours d''eau longs, pression stabilisée, bouclage ECS si pertinent, plusieurs postes (douche + baignoire + double vasque).', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 2, 'Baignoire îlot/balnéo : contraintes techniques ?', 'Alimentation renforcée, vidage performant, contrôle bruit pompe, accès maintenance discret, différentiel dédié.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 3, 'Matériaux premium : que conseillez-vous ?', 'Grès grand format, pierre reconstituée, robinetterie haut de gamme, meubles sur mesure traités contre l''humidité.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 4, 'Douche italienne XXL : pente et écoulement ?', 'Dimensionnement caniveau, pentes régulières, anti-glisse, étanchéité périphérique et joints époxy zones sollicitées.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 5, 'Éclairage architectural : options ?', 'Lignes LED encastrées, scénarios matin/soir, IP adapté volumes, détecteur présence WC séparés si souhaité.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 6, 'PMR/seniors : élégance & sécurité ?', 'Accessoires inox brossé, seuil affleurant, contraste carrelage, circulation fluide, miroir basculant optionnel.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 7, 'Planification et coordination corps d''état ?', 'Planning verrouillé, livraisons groupées, réunions de chantier, tolérance de pose précisée pour chaque lot.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'bondues'), 8, 'SAV et maintenance préventive ?', 'Vérif joints silicone (6–12 mois), réglages, conseils produits d''entretien non agressifs.', true),

  -- La Madeleine FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 1, 'Copropriétés Saint-Maur/Botanique : faisabilité ?', 'Oui, avec information syndic, protection parties communes, évacuation gravats organisée, bruit limité aux créneaux autorisés.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 2, 'Gains de place en appartements compacts ?', 'Receveur 70–80 cm, porte coulissante/verre, meuble 60 cm, colonnes étroites, niches murales, miroir avec rangement.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 3, 'Électricité salle d''eau : sécurité ?', 'Lignes dédiées, différentiel 30 mA, appareillage IP conforme par volumes, liaisons équipotentielles vérifiées.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 4, 'Gestion de l''humidité et des odeurs ?', 'Renfort VMC si besoin, bouches hygro, détalonnage porte, contrôle dépression, joints hydrofuges.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 5, 'PMR en copropriété : comment faire ?', 'Douche à seuil bas, barres d''appui, siège rabattable, circulation dégagée, dossier photos/plan pour validation.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 6, 'Délais et organisation du chantier ?', '7–10 jours, point d''avancement régulier, rebranchement eau/élec chaque soir, ménage quotidien.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 7, 'Choix des matériaux : êtes-vous force de proposition ?', 'Oui, sélection locale showrooms (carrelage, robinets, meubles). Nous proposons 2–3 gammes selon budget.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'la-madeleine'), 8, 'Après-vente et garanties ?', 'Décennale/biennale + SAV 12 mois. Petites retouches couvertes (joints, réglages) sur rendez-vous.', true),

  -- Lambersart FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 1, 'Maisons bourgeoises (Canteleu/Champ-de-Courses) : approche ?', 'Respect du bâti, percements limités, protections renforcées. Esthétique : carrelage grand format, robinetterie design.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 2, 'Douche italienne : rigidité et étanchéité ?', 'Ragréage armé si nécessaire, natte étanche, relevés périphériques, caniveau avec grille affleurante.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 3, 'Baignoire îlot : alimentation/vidage ?', 'Arrivées encastrées, vidage silencieux, accès de maintenance discret, robinetterie sur pied ou murale.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 4, 'Éclairage et confort visuel ?', 'Spots IP65 douche, LED neutre 4000K, miroir antibuée, variateurs hors volume sensible.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 5, 'Acoustique et voisinage ?', 'Anti-vibratiles sur machines, insonorisation évacuations, limitation outils bruyants aux créneaux autorisés.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 6, 'PMR élégante : est-ce possible ?', 'Oui : barres et sièges design, contraste discret mais efficace, circulation fluide, seuil affleurant.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 7, 'Planning et contrôle qualité ?', 'Checkpoints : réseaux, SPEC, calepinage carrelage, finitions. Validation client à chaque étape.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lambersart'), 8, 'Documents remis en fin de chantier ?', 'Notices, plans as-built, fiches d''entretien, attestations de conformité et garanties.', true),

  -- Saint-André-lez-Lille FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 1, 'Maisons mitoyennes : contraintes spécifiques ?', 'Accès étroit, ventilation à optimiser, évacuations à sécuriser. Nous adaptons logistique et planning pour limiter nuisances.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 2, 'Douche italienne en espace réduit : comment faire ?', 'Receveur 80×100 cm, paroi coulissante/pliable, niche de rangement, robinetterie thermostatique.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 3, 'Évacuation/arrivées : mettez-vous aux normes ?', 'Oui : évacuations Ø adaptés, siphons access, PE/Multicouche, vannes d''isolement, test étanchéité avant fermeture.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 4, 'Carrelage durable pour familles ?', 'Grès antidérapant au sol, faïence facile à nettoyer, joints hydrofuges teintés pour tenue esthétique.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 5, 'PMR/seniors : sécurité renforcée ?', 'Sols R10, barres, siège repliable, éclairage d''appoint nocturne, contrastes visuels sur rebords.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 6, 'Délais et communication chantier ?', '7–10 jours. Compte-rendu photos, jalons planifiés, interlocuteur unique joignable.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 7, 'Gestion humidité/odeurs en maisons mitoyennes ?', 'VMC contrôlée/renforcée, bouches hygro, détalonnage porte, joints et pentes conformes.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'saint-andre-lez-lille'), 8, 'Après travaux : conseils d''entretien ?', 'Produits non abrasifs, rinçage régulier parois, contrôle joints silicone 6–12 mois.', true),

  -- Lomme FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 1, 'Quartiers Délivrance/Mitterie : accès et délais ?', 'Accès parfois encombrés : prévoir 0,5 jour logistique. Rénovation complète 7–10 jours comme ailleurs.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 2, 'Optimiser une salle de bains familiale à Lomme ?', 'Rangements suspendus, double vasque 120 cm si possible, douche italienne antidérapante, parois faciles à entretenir.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 3, 'Plomberie : durable et silencieuse ?', 'Réseaux multicouches, colliers anti-bruit, anti-bélier si besoin, évacuations dimensionnées, siphons accessibles.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 4, 'Carrelage et étanchéité : comment garantissez-vous ?', 'SPEC sur zones humides, bandes et angles traités, pentes contrôlées, tests avant pose finale.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 5, 'PMR/seniors : quelles options ?', 'Receveur à fleur, siège rabattable, barres, robinetterie thermostatique, contraste de couleurs et éclairage renforcé.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 6, 'Électricité : sécurité enfants ?', 'Prises hors volume sensible, éclairage IP adapté, différentiel 30 mA, finition antichoc si souhaitée.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 7, 'Ventilation/VMC : évitez-vous la condensation ?', 'Bouches hygro, contrôle dépression, détalonnage porte, rappel entretien filtres et bouches.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lomme'), 8, 'SAV et garanties à Lomme ?', 'Décennale/biennale, SAV 12 mois, retouches de joints et réglages inclus sur rendez-vous.', true);