-- Create testimonials for Pompe à chaleur Lille
INSERT INTO testimonials (service_id, city_id, author_name, location, content, rating, published) VALUES
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Clémence', 'Vieux-Lille', 'Remplacement de ma vieille chaudière par une PAC air/eau. Pose propre en cuisine + cour intérieure, bruit maîtrisé. Conso en baisse.', 5, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Adrien', 'Wazemmes', 'Bonne étude et dimensionnement : radiateurs existants conservés, confort OK en hiver. Réglages pédagogiques.', 5, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Sofia', 'Vauban', 'Contrat d''entretien rassurant : contrôle régulation, mise à jour de la loi d''eau et test d''appoint. Très pro.', 4, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Guillaume', 'Fives', 'Dépannage rapide en janvier (givre récurrent). Diagnostic, dégivrage efficace, correction du positionnement de la sonde.', 5, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Lina', 'Saint-Maurice Pellevoisin', 'PAC + ballon ECS installés en une journée et demie. Bruit extérieur mesuré, voisins rassurés.', 5, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Martin', 'Hellemmes', 'Désembouage + équilibrage après pose : la PAC tourne bas, confort stable, facture maîtrisée.', 5, true);

-- Create FAQs for Pompe à chaleur Lille
INSERT INTO service_city_faqs (service_id, city_id, question, answer, position, published) VALUES
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'PAC air/eau ou air/air : laquelle choisir à Lille ?', 'La PAC air/eau alimente vos radiateurs/plan cher et peut produire l''ECS ; c''est la solution la plus courante en remplacement d''une chaudière. La PAC air/air chauffe via unités intérieures (pas d''ECS) et convient bien aux logements compacts ou en appoint.', 1, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Une PAC fonctionne-t-elle bien l''hiver à Lille ?', 'Oui, à condition d''un dimensionnement sérieux et d''une loi d''eau bien réglée. On vise un fonctionnement à basse température avec radiateurs correctement dimensionnés ou plancher chauffant. En cas de pics de froid, un appoint (électrique ou chaudière existante) peut prendre le relais.', 2, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Ma copropriété du centre impose des règles de bruit : est-ce compatible ?', 'Oui. Nous sélectionnons des unités extérieures silencieuses, ajoutons si besoin des plots antivibratiles, cloisons acoustiques et respectons les distances vis-à-vis des fenêtres/mitoyennetés. Nous fournissons les fiches acoustiques pour le dossier copropriété.', 3, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Peut-on garder mes radiateurs en fonte à Lille ?', 'Souvent oui, surtout s''ils sont nombreux et de bonne surface d''échange. Nous vérifions les températures de départ requises, réalisons un désembouage et rééquilibrons les débits. Si nécessaire, on remplace quelques émetteurs par des modèles basse température.', 4, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Quelle consommation et quelles économies espérer ?', 'Dépend de l''isolation, des émetteurs et de l''usage. L''objectif est un SCOP élevé (PAC bien dimensionnée + réglages fins), ce qui réduit la conso par rapport au gaz/fioul. Nous simulons votre cas pour donner une projection chiffrée et optimiser les réglages après pose.', 5, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Quelles aides pour une PAC à Lille ?', 'Selon votre situation, vous pouvez prétendre à des aides (type MaPrimeRénov'', CEE). Nous aidons à vérifier l''éligibilité, à monter le dossier et à fournir les justificatifs (devis normalisé, attestations de pose, certificats).', 6, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Faut-il un entretien annuel ?', 'Recommandé (et obligatoire au-delà d''un certain seuil de fluide). Nous contrôlons étanchéité, rendement, dégivrage, circulateur, paramètres de régulation et propreté des échangeurs. Un entretien régulier maximise longévité et économies.', 7, true),
  ((SELECT id FROM services WHERE slug = 'pompe-a-chaleur'), (SELECT id FROM cities WHERE slug = 'lille'), 'Où installer l''unité extérieure en ville ?', 'De préférence en cour intérieure ou en façade non exposée aux pièces de nuit, sur supports antivibratiles, avec dégagement suffisant pour l''air et le dégivrage. Nous gérons les évacuations des condensats et proposons des solutions antigivre adaptées à l''hiver lillois.', 8, true);