-- Add service city FAQs for renovation-salle-de-bain
-- Delete existing FAQs first
DELETE FROM service_city_faqs 
WHERE service_id = (SELECT id FROM services WHERE slug = 'renovation-salle-de-bain');

-- Insert all FAQs for all cities
INSERT INTO service_city_faqs (service_id, city_id, position, question, answer, published)
VALUES
  -- Lille FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 1, 'Quels délais pour rénover une salle de bains à Lille ?', 'Comptez 7–10 jours ouvrés pour une rénovation complète (démolition, plomberie, étanchéité, carrelage, électricité, finitions). En hyper-centre ou Fives, un surcroît logistique (stationnement, évacuation gravats) peut ajouter 0,5–1 jour.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 2, 'Gérez-vous les contraintes d''immeuble (copropriété, bruit, horaires) ?', 'Oui. Nous informons le syndic et respectons les créneaux autorisés (bruit, parties communes). Protection des sols/ascenseurs, stockage en appartement, évacuation quotidienne des gravats.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 3, 'Travaux aux normes : quelles références suivez-vous ?', 'Plomberie selon DTU 60.11/60.1, électricité salle d''eau selon NF C 15-100 (volumes 0/1/2), étanchéité SPEC (receveur/angles), ventilation conforme (VMC). Attestations remises en fin de chantier.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 4, 'Petites salles de bains : comment optimiser l''espace ?', 'Meubles suspendus 40–45 cm, receveur extra-plat 70–80 cm, combiné bain-douche, portes coulissantes, niches carrelées. Plan 3D livré avant travaux pour valider chaque cm.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 5, 'Faites-vous des salles de bains PMR/seniors à Lille ?', 'Oui : douche italienne antidérapante (≥ R10), barres d''appui, siège rabattable, mitigeur thermostatique, seuils <2 cm, éclairage renforcé. Conseils d''ergonomie pièce par pièce.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 6, 'Quelles garanties et assurances proposez-vous ?', 'Décennale sur les ouvrages, biennale sur équipements posés, responsabilité civile. Dossier de fin de travaux : notices, plans as-built, factures et conseils d''entretien.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 7, 'La ventilation et l''hygiène d''air sont-elles traitées ?', 'Oui : contrôle de tirage VMC, ajout/renfort si besoin, bouches hygroréglables, détalonnage porte. Objectif : limiter condensation, moisissures et odeurs.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'lille'), 8, 'Comment se déroule le chantier au quotidien ?', 'Chef de chantier unique, point d''avancement tous les 2–3 jours, protection et nettoyage quotidien, coupure d''eau/élec limitée (rebranchement chaque soir).', true),

  -- Vieux-Lille FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 1, 'Appartements anciens : quels points d''attention au Vieux-Lille ?', 'Murs non plans, réseaux anciens, portage étage. Nous redressons les supports, sécurisons les évacuations, limitons les percements et protégeons les parties communes.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 2, 'Douche italienne en bâti ancien : faisable ?', 'Oui, après étude des pentes et étanchéité SPEC/receveur extra-plat. Siphon bas, rehausse minimale, ragréage et natte d''étanchéité en plein champ.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 3, 'Bruit et voisinage : comment limiter les nuisances ?', 'Créneaux courts pour outils bruyants, aspiration intégrée, conditionnement des gravats, communication préalable avec voisins/syndic.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 4, 'Esthétique : peut-on conserver le cachet ?', 'Oui : carrelage métro, faïence posée joint fin, robinetterie design, meubles compacts. Nous soignons les alignements et finitions d''angle.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 5, 'Électricité salle d''eau en immeuble ancien : conforme ?', 'Mise à la terre, différentiel 30 mA dédié salle d''eau, IPX approprié par volume, lignes neuves si nécessaires, repérage tableau mis à jour.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 6, 'PMR dans petites salles de bains : possible ?', 'Oui : bac 80×100 cm mini, barre d''appui, siège repliable, mitigeur accessible, poignée de porte adaptée, miroirs bas. Optimisation 3D incluse.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 7, 'Délais et accès difficiles (rue étroite) : impact ?', 'Prévoir 0,5 jour de logistique. Nous planifions les rotations gravats et sécurisons l''acheminement des matériaux par cage d''escalier.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'vieux-lille'), 8, 'Suivi de chantier : comment êtes-vous joignables ?', 'Un interlocuteur unique (chef de chantier) + messagerie partagée pour photos/jalons. Réponses sous 24 h ouvrées.', true),

  -- Villeneuve-d'Ascq FAQs
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 1, 'Familles vs étudiants : adaptez-vous les solutions ?', 'Oui. Familles : rangements, double vasque, douche facile d''entretien. Étudiants : solutions compactes, combiné bain-douche, robinetterie robuste.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 2, 'Délais typiques à Annappes/Brigode/Flers-Bourg ?', '7–10 jours ouvrés pour une rénovation complète. Coordination plombier-carreleur-électricien pour réduire les temps morts.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 3, 'Carrelages et joints : durabilité ?', 'Grès cérame antidérapant au sol, faïence lessivable au mur, joints hydrofuges, pentes contrôlées en douche.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 4, 'Ventilation en logements des résidences étudiantes ?', 'Contrôle VMC, ajout d''entrées d''air si besoin, bouches hygro, rappel d''entretien filtres et grille de reprise.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 5, 'Budget maîtrisé : comment procéder ?', 'Devis détaillé par lot (plomberie/élec/sols/mobilier), variantes chiffrées (receveur/italienne, meuble 60/80 cm), planning ferme.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 6, 'PMR/seniors : qu''intégrez-vous ?', 'Accès sans marche, dalle renforcée si siège fixe, barres d''appui, sol R10, éclairage non éblouissant, cheminement dégagé.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 7, 'Garantie et SAV après travaux ?', 'Décennale/biennale + SAV sous 12 mois : réglages, joints à reprendre, conseils d''entretien préventif.', true),
  ((SELECT id FROM services WHERE slug = 'renovation-salle-de-bain'), (SELECT id FROM cities WHERE slug = 'villeneuve-d-ascq'), 8, 'Coordination avec le syndic (copro campus) ?', 'Dossier d''information, respect des horaires, dépôt des protections parties communes, main courante de chantier partagée.', true);