// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpwqdkznbmqwvvxpthhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwd3Fka3puYm1xd3Z2eHB0aGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODA1OTAsImV4cCI6MjA3MjY1NjU5MH0.K4yFyinsjcneqLSGXTMbVCcNow9HroVuIYlyi3rD2yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});